version: "2.0"

services:
  drupal:
    container_name: "syndo-drupal"
    build: docker
    ports: 
      - "8080:80"
    volumes:
      - ./drupal/modules:/var/www/html/modules:Z
      - ./drupal/profiles:/var/www/html/profiles:Z
      - ./drupal/themes:/var/www/html/themes:Z
      - ./drupal/sites:/var/www/html/sites:Z
    restart: always

  mysql:
    container_name: "syndo-mysql"
    image: mysql:5.6
    ports: 
      - "3306:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:z
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: syndoecommercedb
      MYSQL_USER: syndoecommercedb
      MYSQL_PASSWORD: syndoecommercedb
