<?php

/**
 * @file
 * Contains syndo_ecommerce.module
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\syndo_ecommerce\Api\Client\Domain\Model\Client;


include 'libs/produto.php';
include 'libs/categoria.php';
include 'libs/campo.php';

/**
 * Implements hook_theme().
 */
function syndo_ecommerce_theme($existing, $type, $theme, $path) {
  $variables = array(
    'form__syndo_ecommerce_form' => array(
      'render element' => 'form',
      'template' => 'form--syndo_ecommerce--form',
    ),
  );
  return $variables;
}

function syndo_ecommerce_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    array_unshift($form['#validate'], 'syndo_ecommerce_user_register_form_validate');
    $form['data'] = [];

    $form['data']['cpf'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('CPF'),
    ];

    $form['data']['nome'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Nome Completo'),
    ];

    $form['data']['zipcode'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('CEP'),
    ];

    $form['data']['birthdate'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Data de Nascimento'),
    ];

    $form['data']['phone'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Telefone'),
    ];

    $form['data']['gender'] = [
        '#type' => 'select',
        '#required' => TRUE,
        '#title' => t('Gênero'),
        '#options' => [
            'male' => t('Masculino'),
            'female' => t('Feminino'),
        ]
    ];
}

function syndo_ecommerce_form_alter(&$form, FormStateInterface $form_state, $form_id) {

}

function syndo_ecommerce_entity_type_alter(array &$entity_types) {
}

function syndo_ecommerce_form_node_product_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    array_unshift($form['actions']['submit']['#submit'], 'syndo_ecommerce_node_product_form_submit');

//    array_unshift($form['#validate'], 'syndo_ecommerce_node_product_form_validate');
//    var_dump($form['actions']['submit']['#submit']);
//    var_dump($form['#validate']);
//    var_dump(array_keys($form));    

    $form['data'] = [

    ];

    $form['data']['codigo'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Codigo Produto'),
    ];

    $categorias = consultarCategoria();

	$options = array();
	foreach ($categorias as $categoria) {
    	$options[$categoria["idcategoria"]] = $categoria["nome"];
	}


    $form['data']['idcategoria'] = [
        '#type' => 'select',
        '#required' => TRUE,
        '#title' => t('Categoria'),
        '#options' => $options
    ];    

    $form['data']['preco'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Preço'),
    ];

    $form['data']['peso'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Peso'),
    ];

    $form['data']['dimensao_a'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Altura'),
    ];

    $form['data']['dimensao_c'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Comprimento'),
    ];    

    $form['data']['dimensao_l'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Largura'),
    ];

    $campos = consultarCampos();
	foreach ($campos as $campo) {
		$form['data'][str_replace(' ','', $campo["nome"])] = [
        	'#type' => 'textfield',
        	'#required' => FALSE,
        	'#title' => t($campo["nome"]),
    	];
	}



	$form['imagem'] = array(
		'#title' => t('Imagem'),
		'#type' => 'managed_file',
		'#upload_location' => 'public://image_example_images/',
	);    
	//https://stackoverflow.com/questions/21214526/how-to-add-image-field-in-form-drupal-7?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

	$form['field_idproduto']['#access'] = FALSE;
}

function syndo_ecommerce_form_node_sac_form_alter(&$form, FormStateInterface $form_state, $form_id) {
//    array_unshift($form['actions']['submit']['#submit'], 'syndo_ecommerce_node_product_form_submit');   

    $form['data'] = [

    ];


}

function syndo_ecommerce_form_node_product_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
//    array_unshift($form['actions']['submit']['#submit'], 'syndo_ecommerce_node_product_form_submit');

//    array_unshift($form['#validate'], 'syndo_ecommerce_node_product_form_validate');
//    var_dump($form['actions']['submit']['#submit']);
//    var_dump($form['#validate']);
//    var_dump(array_keys($form));    

	$form['field_idproduto']['#disabled'] = TRUE;

//	$json = visualizarDadosProduto($form_state->getValue('field_idproduto'));

    $form['data'] = [

    ];

    $form['data']['codigo'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Codigo Produto'),
    ];

    $categorias = consultarCategoria();

	$options = array();
	foreach ($categorias as $categoria) {
    	$options[$categoria["idcategoria"]] = $categoria["nome"];
	}


    $form['data']['idcategoria'] = [
        '#type' => 'select',
        '#required' => TRUE,
        '#title' => t('Categoria'),
        '#options' => $options
    ];    

    $form['data']['preco'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Preço'),
    ];

    $form['data']['peso'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Peso'),
    ];

    $form['data']['dimensao_a'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Altura'),
    ];

    $form['data']['dimensao_c'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Comprimento'),
    ];    

    $form['data']['dimensao_l'] = [
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => t('Largura'),
    ];

    $campos = consultarCampos();
	foreach ($campos as $campo) {
		$form['data'][str_replace(' ','', $campo["nome"])] = [
        	'#type' => 'textfield',
        	'#required' => FALSE,
        	'#title' => t($campo["nome"]),
    	];
	}



	$form['imagem'] = array(
		'#title' => t('Imagem'),
		'#type' => 'managed_file',
		'#upload_location' => 'public://image_example_images/',
	);    
	//https://stackoverflow.com/questions/21214526/how-to-add-image-field-in-form-drupal-7?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
}

function syndo_ecommerce_user_register_form_validate(&$form, FormStateInterface $form_state) {

    $newUser = new Client(
        '',
        $form_state->getValue('nome'),
        $form_state->getValue('mail'),
        $form_state->getValue('zipcode'),
        $form_state->getValue('phone'),
        '',
        $form_state->getValue('cpf'),
        $form_state->getValue('gender'),
        $form_state->getValue('birthdate'),
        ''
    );

    $newUser->save();

    $form_state->setError($form['data']['cpf'], 'Something went wrong');
}

function syndo_ecommerce_user_register_form_submit(&$form, FormStateInterface $form_state) {
//    var_dump($form_state->getValues());
//    var_dump($form_state->getValue('preco'));

}


function syndo_ecommerce_node_product_form_submit(&$form, FormStateInterface $form_state) {
//    var_dump($form_state->getValues());
// 	  var_dump($form_state->getValue('dimensao_c'));


	$array_campos = array();

	$campos = consultarCampos();

	foreach ($campos as $campo) {
		array_push($array_campos, array( 
			"idcampo" => $campo["idcampo"],
			"valor" => $form_state->getValue(str_replace(' ','', $campo["nome"])))
		);		
	}


	$idproduto = cadastrarProduto($form_state->getValue('codigo'), $form_state->getValue('title')[0]['value'], $form_state->getValue('idcategoria'), $form_state->getValue('preco'), $form_state->getValue('peso'), $form_state->getValue('dimensao_a'), $form_state->getValue('dimensao_c'), $form_state->getValue('dimensao_l'), 'img.jpg', $array_campos);

	$array = array(
		array("value" => $idproduto),
	);

	$form_state->setValue('field_idproduto', $array);


}